common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: m
  password: # from psql setup, see Postgresql

development:
  <<: *common
  database: sample_app_development

test:
  <<: *common
  database: sample_app_test

production:
  <<: *common
  database: sample_app_production