common: &common
  adapter: postgresql
  username: postgres
  password: 321321lJ # from psql setup, see Postgresql

development:
  <<: *common
  database: sample_app_development

test:
  <<: *common
  database: sample_app_test

production:
  <<: *common
  database: sample_app_production